<?php
/**
 * Uitgebreide lijst van Nederlandse steden en plaatsen (+ Antwerpen).
 * Formaat: [naam, provincie]
 * De slug wordt automatisch gegenereerd.
 */

return [
    // ---- Groningen ----
    ['Groningen', 'Groningen'], ['Appingedam', 'Groningen'], ['Delfzijl', 'Groningen'],
    ['Winschoten', 'Groningen'], ['Veendam', 'Groningen'], ['Stadskanaal', 'Groningen'],
    ['Hoogezand', 'Groningen'], ['Sappemeer', 'Groningen'], ['Leek', 'Groningen'],
    ['Haren', 'Groningen'], ['Bedum', 'Groningen'], ['Uithuizen', 'Groningen'],
    ['Uithuizermeeden', 'Groningen'], ['Loppersum', 'Groningen'], ['Slochteren', 'Groningen'],
    ['Zuidhorn', 'Groningen'], ['Grootegast', 'Groningen'], ['Ten Boer', 'Groningen'],
    ['Ten Post', 'Groningen'], ['Winsum', 'Groningen'], ['Sauwerd', 'Groningen'],
    ['Middelstum', 'Groningen'], ['Stedum', 'Groningen'], ['Warffum', 'Groningen'],
    ['Roodeschool', 'Groningen'], ['Marum', 'Groningen'], ['Nuis', 'Groningen'],
    ['Eelde', 'Drenthe'], ['Zuidlaren', 'Drenthe'], ['Vlagtwedde', 'Groningen'],
    ['Ter Apel', 'Groningen'], ['Musselkanaal', 'Groningen'], ['Borgercompagnie', 'Groningen'],
    ['Schildwolde', 'Groningen'], ['Foxhol', 'Groningen'], ['Kropswolde', 'Groningen'],
    ['Enumatil', 'Groningen'], ['Noordbroek', 'Groningen'], ['Zuidbroek', 'Groningen'],
    ['Scheemda', 'Groningen'], ['Finsterwolde', 'Groningen'], ['Bad Nieuweschans', 'Groningen'],
    ['Oude Pekela', 'Groningen'], ['Nieuwe Pekela', 'Groningen'], ['Eenrum', 'Groningen'],
    ['Kloosterburen', 'Groningen'], ['Leens', 'Groningen'], ['Ulrum', 'Groningen'],

    // ---- Friesland ----
    ['Leeuwarden', 'Friesland'], ['Sneek', 'Friesland'], ['Heerenveen', 'Friesland'],
    ['Drachten', 'Friesland'], ['Harlingen', 'Friesland'], ['Franeker', 'Friesland'],
    ['Joure', 'Friesland'], ['Wolvega', 'Friesland'], ['Dokkum', 'Friesland'],
    ['Bolsward', 'Friesland'], ['IJlst', 'Friesland'], ['Lemmer', 'Friesland'],
    ['Koudum', 'Friesland'], ['Workum', 'Friesland'], ['Hindeloopen', 'Friesland'],
    ['Stavoren', 'Friesland'], ['Sloten', 'Friesland'], ['Buitenpost', 'Friesland'],
    ['Burgum', 'Friesland'], ['Wommels', 'Friesland'], ['Holwerd', 'Friesland'],
    ['Anjum', 'Friesland'], ['Kollum', 'Friesland'], ['Surhuisterveen', 'Friesland'],
    ['Oosterwolde', 'Friesland'], ['Gorredijk', 'Friesland'], ['Akkrum', 'Friesland'],
    ['Grou', 'Friesland'], ['Makkum', 'Friesland'], ['Hylten', 'Friesland'],
    ['Balk', 'Friesland'], ['Sint Nicolaasga', 'Friesland'], ['Tjerkwerd', 'Friesland'],
    ['Sexbierum', 'Friesland'], ['Sint Annaparochie', 'Friesland'], ['Minnertsga', 'Friesland'],
    ['Ferwert', 'Friesland'], ['Birdaard', 'Friesland'], ['Hallum', 'Friesland'],
    ['Marrum', 'Friesland'], ['Tzummarum', 'Friesland'], ['Dronryp', 'Friesland'],
    ['Deinum', 'Friesland'], ['Winsum', 'Friesland'], ['Eastermar', 'Friesland'],
    ['Sumar', 'Friesland'], ['Hurdegaryp', 'Friesland'], ['Rinsumageest', 'Friesland'],
    ['Damwâld', 'Friesland'], ['Feanwâlden', 'Friesland'], ['Twijzel', 'Friesland'],
    ['Haulerwijk', 'Friesland'], ['Donkerbroek', 'Friesland'], ['Appelscha', 'Friesland'],
    ['Oldeberkoop', 'Friesland'], ['Noordwolde', 'Friesland'], ['De Knipe', 'Friesland'],
    ['Oranjewoud', 'Friesland'], ['Nes', 'Friesland'], ['Ballum', 'Friesland'],
    ['Hollum', 'Friesland'], ['West-Terschelling', 'Friesland'], ['Oudeschild', 'Friesland'],

    // ---- Drenthe ----
    ['Assen', 'Drenthe'], ['Emmen', 'Drenthe'], ['Hoogeveen', 'Drenthe'],
    ['Meppel', 'Drenthe'], ['Coevorden', 'Drenthe'], ['Klazienaveen', 'Drenthe'],
    ['Beilen', 'Drenthe'], ['Roden', 'Drenthe'], ['Norg', 'Drenthe'],
    ['Vries', 'Drenthe'], ['Annen', 'Drenthe'], ['Gieten', 'Drenthe'],
    ['Gasselte', 'Drenthe'], ['Borger', 'Drenthe'], ['Exloo', 'Drenthe'],
    ['Valthe', 'Drenthe'], ['Ter Apel', 'Drenthe'], ['Emmer-Compascuum', 'Drenthe'],
    ['Erica', 'Drenthe'], ['Nieuw-Amsterdam', 'Drenthe'], ['Zwartemeer', 'Drenthe'],
    ['Schoonebeek', 'Drenthe'], ['Dalerveen', 'Drenthe'], ['Weiteveen', 'Drenthe'],
    ['Hollandscheveld', 'Drenthe'], ['Nieuweroord', 'Drenthe'], ['Elim', 'Drenthe'],
    ['Pesse', 'Drenthe'], ['Diever', 'Drenthe'], ['Dwingeloo', 'Drenthe'],
    ['Havelte', 'Drenthe'], ['Vledder', 'Drenthe'], ['Frederiksoord', 'Drenthe'],
    ['Wilhelminaoord', 'Drenthe'], ['Uffelte', 'Drenthe'], ['Ruinen', 'Drenthe'],
    ['Ruinerwold', 'Drenthe'], ['De Wijk', 'Drenthe'], ['Koekange', 'Drenthe'],
    ['Zuidwolde', 'Drenthe'], ['Alteveer', 'Drenthe'], ['Kerkenveld', 'Drenthe'],
    ['Nieuw-Buinen', 'Drenthe'], ['Stadskanaal', 'Drenthe'], ['Eext', 'Drenthe'],
    ['Schoonloo', 'Drenthe'], ['Grolloo', 'Drenthe'], ['Rolde', 'Drenthe'],
    ['Balloo', 'Drenthe'], ['Wittelte', 'Drenthe'],

    // ---- Overijssel ----
    ['Zwolle', 'Overijssel'], ['Enschede', 'Overijssel'], ['Deventer', 'Overijssel'],
    ['Hengelo', 'Overijssel'], ['Almelo', 'Overijssel'], ['Kampen', 'Overijssel'],
    ['Hardenberg', 'Overijssel'], ['Nijverdal', 'Overijssel'], ['Raalte', 'Overijssel'],
    ['Oldenzaal', 'Overijssel'], ['Steenwijk', 'Overijssel'], ['Vollenhove', 'Overijssel'],
    ['Rijssen', 'Overijssel'], ['Dalfsen', 'Overijssel'], ['Genemuiden', 'Overijssel'],
    ['IJsselmuiden', 'Overijssel'], ['Haaksbergen', 'Overijssel'], ['Borne', 'Overijssel'],
    ['Wierden', 'Overijssel'], ['Ommen', 'Overijssel'], ['Den Ham', 'Overijssel'],
    ['Vriezenveen', 'Overijssel'], ['Vroomshoop', 'Overijssel'], ['Daarlerveen', 'Overijssel'],
    ['Tubbergen', 'Overijssel'], ['Albergen', 'Overijssel'], ['Geesteren', 'Overijssel'],
    ['Langeveen', 'Overijssel'], ['Mander', 'Overijssel'], ['Reutum', 'Overijssel'],
    ['Rossum', 'Overijssel'], ['Saasveld', 'Overijssel'], ['Weerselo', 'Overijssel'],
    ['Hertme', 'Overijssel'], ['Zenderen', 'Overijssel'], ['Deurningen', 'Overijssel'],
    ['Losser', 'Overijssel'], ['Overdinkel', 'Overijssel'], ['De Lutte', 'Overijssel'],
    ['Glanerbrug', 'Overijssel'], ['Boekelo', 'Overijssel'], ['Usselo', 'Overijssel'],
    ['Beckum', 'Overijssel'], ['Bentelo', 'Overijssel'], ['Delden', 'Overijssel'],
    ['Hengevelde', 'Overijssel'], ['Wegdam', 'Overijssel'], ['Diepenheim', 'Overijssel'],
    ['Markelo', 'Overijssel'], ['Goor', 'Overijssel'], ['Enter', 'Overijssel'],
    ['Holten', 'Overijssel'], ['Lemele', 'Overijssel'], ['Heino', 'Overijssel'],
    ['Heeten', 'Overijssel'], ['Luttenberg', 'Overijssel'], ['Laag Zuthem', 'Overijssel'],
    ['Broekland', 'Overijssel'], ['Mariënheem', 'Overijssel'], ['Wesepe', 'Overijssel'],
    ['Olst', 'Overijssel'], ['Wijhe', 'Overijssel'], ['Heerde', 'Overijssel'],
    ['Hattem', 'Overijssel'], ['Wezep', 'Overijssel'], ['Zalk', 'Overijssel'],
    ['Mastebroek', 'Overijssel'], ['Nieuwleusen', 'Overijssel'], ['Balkbrug', 'Overijssel'],
    ['Dedemsvaart', 'Overijssel'], ['Avereest', 'Overijssel'], ['Gramsbergen', 'Overijssel'],
    ['Ane', 'Overijssel'], ['Schoonebeek', 'Overijssel'], ['Slagharen', 'Overijssel'],
    ['Brucht', 'Overijssel'], ['Heemserveen', 'Overijssel'], ['Rheeze', 'Overijssel'],
    ['Bergentheim', 'Overijssel'], ['Mariënberg', 'Overijssel'], ['Beerze', 'Overijssel'],
    ['Witharen', 'Overijssel'], ['Punthorst', 'Overijssel'], ['Staphorst', 'Overijssel'],
    ['Rouveen', 'Overijssel'], ['Nieuwleusen', 'Overijssel'], ['Blokzijl', 'Overijssel'],
    ['Kuinder', 'Overijssel'], ['Sint Jansklooster', 'Overijssel'], ['Wanneperveen', 'Overijssel'],
    ['Giethoorn', 'Overijssel'], ['Belt-Schutsloot', 'Overijssel'], ['Zwartsluis', 'Overijssel'],
    ['Hasselt', 'Overijssel'], ['Mastenbroek', 'Overijssel'], ['Genemuiden', 'Overijssel'],

    // ---- Flevoland ----
    ['Almere', 'Flevoland'], ['Lelystad', 'Flevoland'], ['Emmeloord', 'Flevoland'],
    ['Urk', 'Flevoland'], ['Dronten', 'Flevoland'], ['Zeewolde', 'Flevoland'],
    ['Biddinghuizen', 'Flevoland'], ['Swifterbant', 'Flevoland'], ['Tollebeek', 'Flevoland'],
    ['Marknesse', 'Flevoland'], ['Kraggenburg', 'Flevoland'], ['Ens', 'Flevoland'],
    ['Nagele', 'Flevoland'], ['Creil', 'Flevoland'], ['Rutten', 'Flevoland'],
    ['Espel', 'Flevoland'], ['Luttelgeest', 'Flevoland'], ['Bant', 'Flevoland'],

    // ---- Gelderland ----
    ['Arnhem', 'Gelderland'], ['Nijmegen', 'Gelderland'], ['Apeldoorn', 'Gelderland'],
    ['Ede', 'Gelderland'], ['Wageningen', 'Gelderland'], ['Doetinchem', 'Gelderland'],
    ['Winterswijk', 'Gelderland'], ['Zutphen', 'Gelderland'], ['Harderwijk', 'Gelderland'],
    ['Ermelo', 'Gelderland'], ['Putten', 'Gelderland'], ['Nijkerk', 'Gelderland'],
    ['Barneveld', 'Gelderland'], ['Tiel', 'Gelderland'], ['Culemborg', 'Gelderland'],
    ['Buren', 'Gelderland'], ['Zaltbommel', 'Gelderland'], ['Geldermalsen', 'Gelderland'],
    ['Nunspeet', 'Gelderland'], ['Elburg', 'Gelderland'], ['Wezep', 'Gelderland'],
    ['Epe', 'Gelderland'], ['Vaassen', 'Gelderland'], ['Heerde', 'Gelderland'],
    ['Hattem', 'Gelderland'], ['Dieren', 'Gelderland'], ['Rheden', 'Gelderland'],
    ['Velp', 'Gelderland'], ['Duiven', 'Gelderland'], ['Westervoort', 'Gelderland'],
    ['Zevenaar', 'Gelderland'], ['Doesburg', 'Gelderland'], ['Lochem', 'Gelderland'],
    ['Groenlo', 'Gelderland'], ['Lichtenvoorde', 'Gelderland'], ['Aalten', 'Gelderland'],
    ['Bredevoort', 'Gelderland'], ['Neede', 'Gelderland'], ['Borculo', 'Gelderland'],
    ['Eibergen', 'Gelderland'], ['Haarlo', 'Gelderland'], ['Ruurlo', 'Gelderland'],
    ['Zelhem', 'Gelderland'], ['Hengelo', 'Gelderland'], ['Keijenborg', 'Gelderland'],
    ['Humsteren', 'Gelderland'], ['Toldijk', 'Gelderland'], ['Vorden', 'Gelderland'],
    ['Bronkhorst', 'Gelderland'], ['Steenderen', 'Gelderland'], ['Brummen', 'Gelderland'],
    ['Eerbeek', 'Gelderland'], ['Hall', 'Gelderland'], ['Loenen', 'Gelderland'],
    ['Beekbergen', 'Gelderland'], ['Ugchelen', 'Gelderland'], ['Hoenderloo', 'Gelderland'],
    ['Klarenbeek', 'Gelderland'], ['Teuge', 'Gelderland'], ['Twello', 'Gelderland'],
    ['Voorst', 'Gelderland'], ['Wilp', 'Gelderland'], ['Nijbroek', 'Gelderland'],
    ['Bussloo', 'Gelderland'], ['Terwolde', 'Gelderland'], ['Emst', 'Gelderland'],
    ['Oene', 'Gelderland'], ['Gortel', 'Gelderland'], ['Wissel', 'Gelderland'],
    ['Elspeet', 'Gelderland'], ['Uddel', 'Gelderland'], ['Garderen', 'Gelderland'],
    ['Stroe', 'Gelderland'], ['Kootwijkerbroek', 'Gelderland'], ['Voorthuizen', 'Gelderland'],
    ['Terschuur', 'Gelderland'], ['Zwartebroek', 'Gelderland'], ['Achterveld', 'Gelderland'],
    ['Stroe', 'Gelderland'], ['Lunteren', 'Gelderland'], ['Wekerom', 'Gelderland'],
    ['Otterlo', 'Gelderland'], ['Harskamp', 'Gelderland'], ['Ederveen', 'Gelderland'],
    ['De Klomp', 'Gelderland'], ['Bennekom', 'Gelderland'], ['Lunteren', 'Gelderland'],
    ['Renkum', 'Gelderland'], ['Heelsum', 'Gelderland'], ['Oosterbeek', 'Gelderland'],
    ['Wolfheze', 'Gelderland'], ['Doorwerth', 'Gelderland'], ['Heveadorp', 'Gelderland'],
    ['Ellecom', 'Gelderland'], ['Laag-Soeren', 'Gelderland'], ['Spankeren', 'Gelderland'],
    ['Hoevelaken', 'Gelderland'], ['Stoutenburg', 'Gelderland'], ['Zwartebroek', 'Gelderland'],
    ['Terschuur', 'Gelderland'], ['Kesteren', 'Gelderland'], ['Opheusden', 'Gelderland'],
    ['Dodewaard', 'Gelderland'], ['Andelst', 'Gelderland'], ['Herveld', 'Gelderland'],
    ['Valburg', 'Gelderland'], ['Elst', 'Gelderland'], ['Oosterhout', 'Gelderland'],
    ['Slijk-Ewijk', 'Gelderland'], ['Bemmel', 'Gelderland'], ['Huissen', 'Gelderland'],
    ['Gendt', 'Gelderland'], ['Doornenburg', 'Gelderland'], ['Angeren', 'Gelderland'],
    ['Haalderen', 'Gelderland'], ['Ressen', 'Gelderland'], ['Lent', 'Gelderland'],
    ['Ooij', 'Gelderland'], ['Beek', 'Gelderland'], ['Berg en Dal', 'Gelderland'],
    ['Groesbeek', 'Gelderland'], ['Millingen', 'Gelderland'], ['Malden', 'Gelderland'],
    ['Heumen', 'Gelderland'], ['Overasselt', 'Gelderland'], ['Nederasselt', 'Gelderland'],
    ['Grave', 'Gelderland'], ['Escharen', 'Gelderland'], ['Velp', 'Gelderland'],
    ['Wamel', 'Gelderland'], ['Alphen', 'Gelderland'], ['Puiflijk', 'Gelderland'],
    ['Druten', 'Gelderland'], ['Afferden', 'Gelderland'], ['Deest', 'Gelderland'],
    ['Horssen', 'Gelderland'], ['Ewijk', 'Gelderland'], ['Winssen', 'Gelderland'],
    ['Beuningen', 'Gelderland'], ['Weurt', 'Gelderland'], ['Zetten', 'Gelderland'],
    ['Hemmen', 'Gelderland'], ['Randwijk', 'Gelderland'], ['Heteren', 'Gelderland'],
    ['Driel', 'Gelderland'], ['Bruchem', 'Gelderland'], ['Kerkwijk', 'Gelderland'],
    ['Brakel', 'Gelderland'], ['Poederoijen', 'Gelderland'], ['Heerewaarden', 'Gelderland'],
    ['Rozendaal', 'Gelderland'], ['Maurik', 'Gelderland'], ['Eck en Wiel', 'Gelderland'],
    ['Ingen', 'Gelderland'], ['Ommeren', 'Gelderland'], ['Lienden', 'Gelderland'],
    ['Kesteren', 'Gelderland'], ['Rijswijk', 'Gelderland'], ['Ijzendoorn', 'Gelderland'],
    ['Ochten', 'Gelderland'], ['Echteld', 'Gelderland'], ['IJzendoorn', 'Gelderland'],
    ['Asperen', 'Gelderland'], ['Heukelum', 'Gelderland'], ['Spijk', 'Gelderland'],
    ['Herwijnen', 'Gelderland'], ['Vuren', 'Gelderland'],

    // ---- Utrecht ----
    ['Utrecht', 'Utrecht'], ['Amersfoort', 'Utrecht'], ['Hilversum', 'Utrecht'],
    ['Nieuwegein', 'Utrecht'], ['Zeist', 'Utrecht'], ['Houten', 'Utrecht'],
    ['IJsselstein', 'Utrecht'], ['Veenendaal', 'Utrecht'], ['Rhenen', 'Utrecht'],
    ['Woerden', 'Utrecht'], ['Leusden', 'Utrecht'], ['Soest', 'Utrecht'],
    ['Baarn', 'Utrecht'], ['Bunschoten-Spakenburg', 'Utrecht'], ['Doorn', 'Utrecht'],
    ['Driebergen-Rijsenburg', 'Utrecht'], ['Wijk bij Duurstede', 'Utrecht'],
    ['Montfoort', 'Utrecht'], ['Lopik', 'Utrecht'], ['Leerdam', 'Utrecht'],
    ['Vianen', 'Utrecht'], ['Meerkerk', 'Utrecht'], ['De Meern', 'Utrecht'],
    ['Maarssen', 'Utrecht'], ['Breukelen', 'Utrecht'], ['Maartensdijk', 'Utrecht'],
    ['Bilthoven', 'Utrecht'], ['De Bilt', 'Utrecht'], ['Groenekan', 'Utrecht'],
    ['Hollandsche Rading', 'Utrecht'], ['Loenen aan de Vecht', 'Utrecht'],
    ['Nieuwersluis', 'Utrecht'], ['Kockengen', 'Utrecht'], ['Nieuwer Ter Aa', 'Utrecht'],
    ['Ameide', 'Utrecht'], ['Tienhoven', 'Utrecht'], ['Everdingen', 'Utrecht'],
    ['Hei- en Boeicop', 'Utrecht'], ['Leerbroek', 'Utrecht'], ['Nieuwland', 'Utrecht'],
    ['Schoonrewoerd', 'Utrecht'], ['Kedichem', 'Utrecht'], ['Oosterwijk', 'Utrecht'],
    ['Aarlanderveen', 'Utrecht'], ['Linschoten', 'Utrecht'], ['Papekop', 'Utrecht'],
    ['Hekendorp', 'Utrecht'], ['Haastrecht', 'Utrecht'], ['Stolwijk', 'Utrecht'],
    ['Vlist', 'Utrecht'], ['Willige Langerak', 'Utrecht'], ['Oudewater', 'Utrecht'],
    ['Hoenkoop', 'Utrecht'], ['Snelrewaard', 'Utrecht'], ['Kamerik', 'Utrecht'],
    ['Zegveld', 'Utrecht'], ['Harmelen', 'Utrecht'], ['Vleuten', 'Utrecht'],
    ['Oudenrijn', 'Utrecht'], ['Jutphaas', 'Utrecht'], ['Schalkwijk', 'Utrecht'],
    ['Tull en \'t Waal', 'Utrecht'], ['Bunnik', 'Utrecht'], ['Odijk', 'Utrecht'],
    ['Werkhoven', 'Utrecht'], ['Culemborg', 'Utrecht'], ['Hagestein', 'Utrecht'],
    ['Tull en het Waal', 'Utrecht'], ['Renswoude', 'Utrecht'], ['Scherpenzeel', 'Utrecht'],
    ['Woudenberg', 'Utrecht'], ['Maarn', 'Utrecht'], ['Maarsbergen', 'Utrecht'],
    ['Overberg', 'Utrecht'], ['Amerongen', 'Utrecht'], ['Elst', 'Utrecht'],
    ['Leersum', 'Utrecht'], ['Zuilen', 'Utrecht'], ['Oud-Zuilen', 'Utrecht'],
    ['Westbroek', 'Utrecht'], ['Tienhoven', 'Utrecht'], ['Achterveld', 'Utrecht'],
    ['Hoogland', 'Utrecht'], ['Hooglanderveen', 'Utrecht'], ['Soesterberg', 'Utrecht'],
    ['Den Dolder', 'Utrecht'], ['Austerlitz', 'Utrecht'], ['Bosch en Duin', 'Utrecht'],
    ['Huis ter Heide', 'Utrecht'], ['Lage Vuursche', 'Utrecht'], ['Hooge Vuursche', 'Utrecht'],
    ['Eembrugge', 'Utrecht'], ['Eemnes', 'Utrecht'], ['Laren', 'Utrecht'],
    ['Blaricum', 'Utrecht'], ['Huizen', 'Utrecht'], ['De Glind', 'Utrecht'],
    ['Stoutenburg Noord', 'Utrecht'], ['Amstelhoek', 'Utrecht'], ['De Hoef', 'Utrecht'],
    ['Mijdrecht', 'Utrecht'], ['Vinkeveen', 'Utrecht'], ['Waverveen', 'Utrecht'],
    ['Abcoude', 'Utrecht'], ['Baambrugge', 'Utrecht'], ['Driemond', 'Utrecht'],

    // ---- Noord-Holland ----
    ['Amsterdam', 'Noord-Holland'], ['Haarlem', 'Noord-Holland'], ['Zaandam', 'Noord-Holland'],
    ['Alkmaar', 'Noord-Holland'], ['Hoorn', 'Noord-Holland'], ['Den Helder', 'Noord-Holland'],
    ['Amstelveen', 'Noord-Holland'], ['Purmerend', 'Noord-Holland'], ['Hilversum', 'Noord-Holland'],
    ['Hoofddorp', 'Noord-Holland'], ['Nieuw-Vennep', 'Noord-Holland'], ['Badhoevedorp', 'Noord-Holland'],
    ['Beverwijk', 'Noord-Holland'], ['Heemskerk', 'Noord-Holland'], ['IJmuiden', 'Noord-Holland'],
    ['Velsen-Zuid', 'Noord-Holland'], ['Santpoort-Noord', 'Noord-Holland'], ['Santpoort-Zuid', 'Noord-Holland'],
    ['Driehuis', 'Noord-Holland'], ['Velserbroek', 'Noord-Holland'], ['Castricum', 'Noord-Holland'],
    ['Heiloo', 'Noord-Holland'], ['Bergen', 'Noord-Holland'], ['Bergen aan Zee', 'Noord-Holland'],
    ['Egmond aan Zee', 'Noord-Holland'], ['Egmond-Binnen', 'Noord-Holland'], ['Schoorl', 'Noord-Holland'],
    ['Schagen', 'Noord-Holland'], ['Tuitjenhorn', 'Noord-Holland'], ['Warmenhuizen', 'Noord-Holland'],
    ['Langedijk', 'Noord-Holland'], ['Broek op Langedijk', 'Noord-Holland'], ['Noord-Scharwoude', 'Noord-Holland'],
    ['Zuid-Scharwoude', 'Noord-Holland'], ['Obdam', 'Noord-Holland'], ['Hensbroek', 'Noord-Holland'],
    ['Heerhugowaard', 'Noord-Holland'], ['Wognum', 'Noord-Holland'], ['Nibbixwoud', 'Noord-Holland'],
    ['Zwaag', 'Noord-Holland'], ['Hoogkarspel', 'Noord-Holland'], ['Westwoud', 'Noord-Holland'],
    ['Oosterblokker', 'Noord-Holland'], ['Blokker', 'Noord-Holland'], ['Oosterleek', 'Noord-Holland'],
    ['Enkhuizen', 'Noord-Holland'], ['Medemblik', 'Noord-Holland'], ['Wervershoof', 'Noord-Holland'],
    ['Andijk', 'Noord-Holland'], ['Wognum', 'Noord-Holland'], ['Aartswoud', 'Noord-Holland'],
    ['Oudkarspel', 'Noord-Holland'], ['Sint Maarten', 'Noord-Holland'], ['Waarland', 'Noord-Holland'],
    ['Haringhuizen', 'Noord-Holland'], ['Barsingerhorn', 'Noord-Holland'], ['Anna Paulowna', 'Noord-Holland'],
    ['Breezand', 'Noord-Holland'], ['Wieringerwerf', 'Noord-Holland'], ['Middenmeer', 'Noord-Holland'],
    ['Slootdorp', 'Noord-Holland'], ['Hippolytushoef', 'Noord-Holland'], ['Den Oever', 'Noord-Holland'],
    ['Wieringerwaard', 'Noord-Holland'], ['Oudesluis', 'Noord-Holland'], ['Callantsoog', 'Noord-Holland'],
    ['Petten', 'Noord-Holland'], ['Sint Maartensvlotbrug', 'Noord-Holland'], ['Burgerbrug', 'Noord-Holland'],
    ['T Zand', 'Noord-Holland'], ['Julianadorp', 'Noord-Holland'], ['Huisduinen', 'Noord-Holland'],
    ['De Kooy', 'Noord-Holland'], ['Den Burg', 'Noord-Holland'], ['De Koog', 'Noord-Holland'],
    ['Oudeschild', 'Noord-Holland'], ['Den Hoorn', 'Noord-Holland'], ['Oosterend', 'Noord-Holland'],
    ['De Waal', 'Noord-Holland'], ['Volendam', 'Noord-Holland'], ['Edam', 'Noord-Holland'],
    ['Marken', 'Noord-Holland'], ['Monnickendam', 'Noord-Holland'], ['Broek in Waterland', 'Noord-Holland'],
    ['Katwoude', 'Noord-Holland'], ['Purmer', 'Noord-Holland'], ['Ilpendam', 'Noord-Holland'],
    ['Watergang', 'Noord-Holland'], ['Zuiderwoude', 'Noord-Holland'], ['Holysloot', 'Noord-Holland'],
    ['Ransdorp', 'Noord-Holland'], ['Schellingwoude', 'Noord-Holland'], ['Nieuwendam', 'Noord-Holland'],
    ['Durgerdam', 'Noord-Holland'], ['Diemen', 'Noord-Holland'], ['Duivendrecht', 'Noord-Holland'],
    ['Ouderkerk aan de Amstel', 'Noord-Holland'], ['Amsteldijk', 'Noord-Holland'],
    ['Uithoorn', 'Noord-Holland'], ['De Kwakel', 'Noord-Holland'], ['Aalsmeer', 'Noord-Holland'],
    ['Aalsmeerderbrug', 'Noord-Holland'], ['Kudelstaart', 'Noord-Holland'], ['Mijdrecht', 'Noord-Holland'],
    ['Abcoude', 'Noord-Holland'], ['Baambrugge', 'Noord-Holland'], ['Weesp', 'Noord-Holland'],
    ['Driemond', 'Noord-Holland'], ['Muiden', 'Noord-Holland'], ['Muiderberg', 'Noord-Holland'],
    ['Naarden', 'Noord-Holland'], ['Bussum', 'Noord-Holland'], ['Huizen', 'Noord-Holland'],
    ['Blaricum', 'Noord-Holland'], ['Laren', 'Noord-Holland'], ['Eemnes', 'Noord-Holland'],
    ['Krommenie', 'Noord-Holland'], ['Assendelft', 'Noord-Holland'], ['Koog aan de Zaan', 'Noord-Holland'],
    ['Wormerveer', 'Noord-Holland'], ['Westzaan', 'Noord-Holland'], ['Oostzaan', 'Noord-Holland'],
    ['Zaandijk', 'Noord-Holland'], ['Landsmeer', 'Noord-Holland'], ['Den Ilp', 'Noord-Holland'],
    ['Purmerland', 'Noord-Holland'], ['Spijkerboor', 'Noord-Holland'], ['Graft', 'Noord-Holland'],
    ['De Rijp', 'Noord-Holland'], ['Starnmeer', 'Noord-Holland'], ['Oost-Graftdijk', 'Noord-Holland'],
    ['West-Graftdijk', 'Noord-Holland'], ['Noordeinde', 'Noord-Holland'], ['Zuidschermer', 'Noord-Holland'],
    ['Stompetoren', 'Noord-Holland'], ['Ursem', 'Noord-Holland'], ['Rustenburg', 'Noord-Holland'],
    ['Schermerhorn', 'Noord-Holland'], ['Groenveld', 'Noord-Holland'], ['Zuid-Schermer', 'Noord-Holland'],
    ['Limmen', 'Noord-Holland'], ['Akersloot', 'Noord-Holland'], ['De Woude', 'Noord-Holland'],
    ['Bakkum', 'Noord-Holland'], ['Wijk aan Zee', 'Noord-Holland'], ['Heemskerk', 'Noord-Holland'],

    // ---- Zuid-Holland ----
    ['Den Haag', 'Zuid-Holland'], ['Rotterdam', 'Zuid-Holland'], ['Zoetermeer', 'Zuid-Holland'],
    ['Delft', 'Zuid-Holland'], ['Leiden', 'Zuid-Holland'], ['Gouda', 'Zuid-Holland'],
    ['Alphen aan den Rijn', 'Zuid-Holland'], ['Dordrecht', 'Zuid-Holland'],
    ['Spijkenisse', 'Zuid-Holland'], ['Vlaardingen', 'Zuid-Holland'], ['Schiedam', 'Zuid-Holland'],
    ['Capelle aan den IJssel', 'Zuid-Holland'], ['Krimpen aan den IJssel', 'Zuid-Holland'],
    ['Rijswijk', 'Zuid-Holland'], ['Voorburg', 'Zuid-Holland'], ['Leidschendam', 'Zuid-Holland'],
    ['Wassenaar', 'Zuid-Holland'], ['Voorschoten', 'Zuid-Holland'], ['Katwijk', 'Zuid-Holland'],
    ['Noordwijk', 'Zuid-Holland'], ['Lisse', 'Zuid-Holland'], ['Hillegom', 'Zuid-Holland'],
    ['Sassenheim', 'Zuid-Holland'], ['Oegstgeest', 'Zuid-Holland'], ['Leiderdorp', 'Zuid-Holland'],
    ['Zoeterwoude', 'Zuid-Holland'], ['Bodegraven', 'Zuid-Holland'], ['Waddinxveen', 'Zuid-Holland'],
    ['Boskoop', 'Zuid-Holland'], ['Papendrecht', 'Zuid-Holland'], ['Zwijndrecht', 'Zuid-Holland'],
    ['Sliedrecht', 'Zuid-Holland'], ['Gorinchem', 'Zuid-Holland'], ['Hardinxveld-Giessendam', 'Zuid-Holland'],
    ['Alblasserdam', 'Zuid-Holland'], ['Ridderkerk', 'Zuid-Holland'], ['Barendrecht', 'Zuid-Holland'],
    ['Hellevoetsluis', 'Zuid-Holland'], ['Brielle', 'Zuid-Holland'], ['Middelharnis', 'Zuid-Holland'],
    ['Naaldwijk', 'Zuid-Holland'], ['Maassluis', 'Zuid-Holland'], ['Pijnacker', 'Zuid-Holland'],
    ['Nootdorp', 'Zuid-Holland'], ['Delfgauw', 'Zuid-Holland'], ['Hoek van Holland', 'Zuid-Holland'],
    ['Poortugaal', 'Zuid-Holland'], ['Rhoon', 'Zuid-Holland'], ['Albrandswaard', 'Zuid-Holland'],
    ['Heinenoord', 'Zuid-Holland'], ['Mijnsheerenland', 'Zuid-Holland'], ['Westmaas', 'Zuid-Holland'],
    ['Maasdam', 'Zuid-Holland'], ['Puttershoek', 'Zuid-Holland'], ['Klaaswaal', 'Zuid-Holland'],
    ['Numansdorp', 'Zuid-Holland'], ['Zuid-Beijerland', 'Zuid-Holland'], ['Piershil', 'Zuid-Holland'],
    ['Goudswaard', 'Zuid-Holland'], ['Nieuw-Beijerland', 'Zuid-Holland'], ['Hekelingen', 'Zuid-Holland'],
    ['Geervliet', 'Zuid-Holland'], ['Simonshaven', 'Zuid-Holland'], ['Den Bommel', 'Zuid-Holland'],
    ['Oude-Tonge', 'Zuid-Holland'], ['Nieuwe-Tonge', 'Zuid-Holland'], ['Herkingen', 'Zuid-Holland'],
    ['Dirksland', 'Zuid-Holland'], ['Melissant', 'Zuid-Holland'], ['Sommelsdijk', 'Zuid-Holland'],
    ['Ooltgensplaat', 'Zuid-Holland'], ['Ouddorp', 'Zuid-Holland'], ['Goedereede', 'Zuid-Holland'],
    ['Stellendam', 'Zuid-Holland'], ['Rockanje', 'Zuid-Holland'], ['Oostvoorne', 'Zuid-Holland'],
    ['Tinte', 'Zuid-Holland'], ['Vierpolders', 'Zuid-Holland'], ['Zwartewaal', 'Zuid-Holland'],
    ['Heenvliet', 'Zuid-Holland'], ['Abbenbroek', 'Zuid-Holland'], ['Oudenhoorn', 'Zuid-Holland'],
    ['Hellevoetsluis', 'Zuid-Holland'], ['Scheveningen', 'Zuid-Holland'], ['Monster', 'Zuid-Holland'],
    ['\'s-Gravenzande', 'Zuid-Holland'], ['Ter Heijde', 'Zuid-Holland'], ['De Lier', 'Zuid-Holland'],
    ['Kwintsheul', 'Zuid-Holland'], ['Wateringen', 'Zuid-Holland'], ['Poeldijk', 'Zuid-Holland'],
    ['Honselersdijk', 'Zuid-Holland'], ['Hazerswoude-Dorp', 'Zuid-Holland'], ['Hazerswoude-Rijndijk', 'Zuid-Holland'],
    ['Benthuizen', 'Zuid-Holland'], ['Moerkapelle', 'Zuid-Holland'], ['Moordrecht', 'Zuid-Holland'],
    ['Zevenhuizen', 'Zuid-Holland'], ['Nieuwerkerk aan den IJssel', 'Zuid-Holland'], ['Bergschenhoek', 'Zuid-Holland'],
    ['Berkel en Rodenrijs', 'Zuid-Holland'], ['Bleiswijk', 'Zuid-Holland'], ['Reeuwijk', 'Zuid-Holland'],
    ['Waarder', 'Zuid-Holland'], ['Driebruggen', 'Zuid-Holland'], ['Haastrecht', 'Zuid-Holland'],
    ['Stolwijk', 'Zuid-Holland'], ['Vlist', 'Zuid-Holland'], ['Lekkerkerk', 'Zuid-Holland'],
    ['Krimpen aan de Lek', 'Zuid-Holland'], ['Ouderkerk aan den IJssel', 'Zuid-Holland'],
    ['Gouderak', 'Zuid-Holland'], ['Berkenwoude', 'Zuid-Holland'], ['Goverwelle', 'Zuid-Holland'],
    ['Ameide', 'Zuid-Holland'], ['Bleskensgraaf', 'Zuid-Holland'], ['Brandwijk', 'Zuid-Holland'],
    ['Groot-Ammers', 'Zuid-Holland'], ['Langerak', 'Zuid-Holland'], ['Molenaarsgraaf', 'Zuid-Holland'],
    ['Nieuw-Lekkerland', 'Zuid-Holland'], ['Nieuwpoort', 'Zuid-Holland'], ['Ottoland', 'Zuid-Holland'],
    ['Schelluinen', 'Zuid-Holland'], ['Streefkerk', 'Zuid-Holland'], ['Wijngaarden', 'Zuid-Holland'],
    ['Arkel', 'Zuid-Holland'], ['Giessenburg', 'Zuid-Holland'], ['Hoogblokland', 'Zuid-Holland'],
    ['Hoornaar', 'Zuid-Holland'], ['Noordeloos', 'Zuid-Holland'], ['Meerkerk', 'Zuid-Holland'],
    ['Leerbroek', 'Zuid-Holland'], ['Nieuwland', 'Zuid-Holland'], ['Heicop', 'Zuid-Holland'],
    ['Kedichem', 'Zuid-Holland'], ['Oosterwijk', 'Zuid-Holland'], ['Schoonrewoerd', 'Zuid-Holland'],
    ['Leerdam', 'Zuid-Holland'], ['Asperen', 'Zuid-Holland'], ['Herwijnen', 'Zuid-Holland'],
    ['Heukelum', 'Zuid-Holland'], ['Spijk', 'Zuid-Holland'], ['Vuren', 'Zuid-Holland'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['Rijswijk', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['Doeveren', 'Zuid-Holland'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['Heusden', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['Elseng', 'Zuid-Holland'],
    ['Kaatje', 'Zuid-Holland'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['\'s-Gravenmoer', 'Zuid-Holland'], ['%s', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],
    ['%s', 'Noord-Brabant'], ['%s', 'Noord-Brabant'],

    // ---- Zeeland ----
    ['Middelburg', 'Zeeland'], ['Vlissingen', 'Zeeland'], ['Goes', 'Zeeland'],
    ['Terneuzen', 'Zeeland'], ['Hulst', 'Zeeland'], ['Zierikzee', 'Zeeland'],
    ['Oostburg', 'Zeeland'], ['Sluis', 'Zeeland'], ['Axel', 'Zeeland'],
    ['Tholen', 'Zeeland'], ['Sint-Annaland', 'Zeeland'], ['Veere', 'Zeeland'],
    ['Domburg', 'Zeeland'], ['Koudekerke', 'Zeeland'], ['Arnemuiden', 'Zeeland'],
    ['Kapelle', 'Zeeland'], ['Kruiningen', 'Zeeland'], ['Yerseke', 'Zeeland'],
    ['Heinkenszand', 'Zeeland'], ['Borssele', 'Zeeland'], ['Lewedorp', 'Zeeland'],
    ['Nieuwdorp', 'Zeeland'], ['\'s-Heer Arendskerke', 'Zeeland'], ['\'s-Heer Hendrikskinderen', 'Zeeland'],
    ['Wolphaartsdijk', 'Zeeland'], ['Oud-Sabbinge', 'Zeeland'], ['Kattendijke', 'Zeeland'],
    ['Wilhelminadorp', 'Zeeland'], ['Kortgene', 'Zeeland'], ['Colijnsplaat', 'Zeeland'],
    ['Kats', 'Zeeland'], ['Wissenkerke', 'Zeeland'], ['Kamperland', 'Zeeland'],
    ['Geersdijk', 'Zeeland'], ['Annaland', 'Zeeland'], ['Poortvliet', 'Zeeland'],
    ['Scherpenisse', 'Zeeland'], ['Stavenisse', 'Zeeland'], ['Sint-Maartensdijk', 'Zeeland'],
    ['Oud-Vossemeer', 'Zeeland'], ['Bruinisse', 'Zeeland'], ['Dreischor', 'Zeeland'],
    ['Noordgouwe', 'Zeeland'], ['Zonnemaire', 'Zeeland'], ['Brouwershaven', 'Zeeland'],
    ['Burgh-Haamstede', 'Zeeland'], ['Renesse', 'Zeeland'], ['Ellemeet', 'Zeeland'],
    ['Scharendijke', 'Zeeland'], ['Sirjansland', 'Zeeland'], ['Oosterland', 'Zeeland'],
    ['Ouwerkerk', 'Zeeland'], ['Nieuwerkerk', 'Zeeland'], ['Philippine', 'Zeeland'],
    ['Westdorpe', 'Zeeland'], ['Zaamslag', 'Zeeland'], ['Hoek', 'Zeeland'],
    ['Sas van Gent', 'Zeeland'], ['Koewacht', 'Zeeland'], ['Overslag', 'Zeeland'],
    ['Clinge', 'Zeeland'], ['Sint Jansteen', 'Zeeland'], ['Vogelwaarde', 'Zeeland'],
    ['Hontenisse', 'Zeeland'], ['Lamswaarde', 'Zeeland'], ['Terhole', 'Zeeland'],
    ['Kloosterzande', 'Zeeland'], ['Walsoorden', 'Zeeland'], ['Ossenisse', 'Zeeland'],
    ['Graauw', 'Zeeland'], ['Heikant', 'Zeeland'], ['Nieuw Namen', 'Zeeland'],
    ['Hulst', 'Zeeland'], ['Kapellebrug', 'Zeeland'], ['Sint Anna ter Muiden', 'Zeeland'],
    ['Aardenburg', 'Zeeland'], ['Eede', 'Zeeland'], ['Waterlandkerkje', 'Zeeland'],
    ['Hoofdplaat', 'Zeeland'], ['Breskens', 'Zeeland'], ['Nieuwvliet', 'Zeeland'],
    ['Cadzand', 'Zeeland'], ['Retranchement', 'Zeeland'], ['Groede', 'Zeeland'],
    ['Schoondijke', 'Zeeland'], ['IJzendijke', 'Zeeland'], ['Biervliet', 'Zeeland'],

    // ---- Noord-Brabant ----
    ['Eindhoven', 'Noord-Brabant'], ['Tilburg', 'Noord-Brabant'], ['Breda', 'Noord-Brabant'],
    ['\'s-Hertogenbosch', 'Noord-Brabant'], ['Helmond', 'Noord-Brabant'], ['Roosendaal', 'Noord-Brabant'],
    ['Oss', 'Noord-Brabant'], ['Bergen op Zoom', 'Noord-Brabant'], ['Etten-Leur', 'Noord-Brabant'],
    ['Oosterhout', 'Noord-Brabant'], ['Waalwijk', 'Noord-Brabant'], ['Veghel', 'Noord-Brabant'],
    ['Schijndel', 'Noord-Brabant'], ['Sint-Oedenrode', 'Noord-Brabant'], ['Uden', 'Noord-Brabant'],
    ['Boxmeer', 'Noord-Brabant'], ['Cuijk', 'Noord-Brabant'], ['Gemert', 'Noord-Brabant'],
    ['Deurne', 'Noord-Brabant'], ['Geldrop', 'Noord-Brabant'], ['Valkenswaard', 'Noord-Brabant'],
    ['Veldhoven', 'Noord-Brabant'], ['Best', 'Noord-Brabant'], ['Boxtel', 'Noord-Brabant'],
    ['Sint-Michielsgestel', 'Noord-Brabant'], ['Vught', 'Noord-Brabant'], ['Heusden', 'Noord-Brabant'],
    ['Drunen', 'Noord-Brabant'], ['Kaatsheuvel', 'Noord-Brabant'], ['Dongen', 'Noord-Brabant'],
    ['Gilze', 'Noord-Brabant'], ['Rijen', 'Noord-Brabant'], ['Hulten', 'Noord-Brabant'],
    ['Alphen', 'Noord-Brabant'], ['Chaam', 'Noord-Brabant'], ['Baarle-Nassau', 'Noord-Brabant'],
    ['Goirle', 'Noord-Brabant'], ['Riel', 'Noord-Brabant'], ['Oisterwijk', 'Noord-Brabant'],
    ['Hilvarenbeek', 'Noord-Brabant'], ['Bladel', 'Noord-Brabant'], ['Eersel', 'Noord-Brabant'],
    ['Reusel', 'Noord-Brabant'], ['Bergeijk', 'Noord-Brabant'], ['Waalre', 'Noord-Brabant'],
    ['Son en Breugel', 'Noord-Brabant'], ['Nuenen', 'Noord-Brabant'], ['Beek en Donk', 'Noord-Brabant'],
    ['Asten', 'Noord-Brabant'], ['Someren', 'Noord-Brabant'], ['Bakel', 'Noord-Brabant'],
    ['Milheeze', 'Noord-Brabant'], ['Rips', 'Noord-Brabant'], ['Mill', 'Noord-Brabant'],
    ['Sint Anthonis', 'Noord-Brabant'], ['Grave', 'Noord-Brabant'], ['Escharen', 'Noord-Brabant'],
    ['Heesch', 'Noord-Brabant'], ['Berghem', 'Noord-Brabant'], ['Rosmalen', 'Noord-Brabant'],
    ['Vlijmen', 'Noord-Brabant'], ['Nuland', 'Noord-Brabant'], ['Geffen', 'Noord-Brabant'],
    ['Heeswijk-Dinther', 'Noord-Brabant'], ['Loosbroek', 'Noord-Brabant'], ['Wijchen', 'Noord-Brabant'],
    ['Megen', 'Noord-Brabant'], ['Ravenstein', 'Noord-Brabant'], ['Herpen', 'Noord-Brabant'],
    ['Lith', 'Noord-Brabant'], ['Lithoijen', 'Noord-Brabant'], ['Teeffelen', 'Noord-Brabant'],
    ['Oijen', 'Noord-Brabant'], ['Macharen', 'Noord-Brabant'], ['Haren', 'Noord-Brabant'],
    ['Kerkdriel', 'Noord-Brabant'], ['Velddriel', 'Noord-Brabant'], ['Hedel', 'Noord-Brabant'],
    ['Ammerzoden', 'Noord-Brabant'], ['Well', 'Noord-Brabant'], ['Wellseind', 'Noord-Brabant'],
    ['Brakel', 'Noord-Brabant'], ['Poederoijen', 'Noord-Brabant'], ['Zuilichem', 'Noord-Brabant'],
    ['Bern', 'Noord-Brabant'], ['Hedikhuizen', 'Noord-Brabant'], ['Doeveren', 'Noord-Brabant'],
    ['Nieuwkuijk', 'Noord-Brabant'], ['Haarsteeg', 'Noord-Brabant'], ['Vlijmen', 'Noord-Brabant'],
    ['Cromvoirt', 'Noord-Brabant'], ['Helvoirt', 'Noord-Brabant'], ['Esch', 'Noord-Brabant'],
    ['Gemonde', 'Noord-Brabant'], ['Den Dungen', 'Noord-Brabant'], ['Berlicum', 'Noord-Brabant'],
    ['Middelrode', 'Noord-Brabant'], ['Sint-Michielsgestel', 'Noord-Brabant'], ['Berkel-Enschot', 'Noord-Brabant'],
    ['Udenhout', 'Noord-Brabant'], ['Biezenmortel', 'Noord-Brabant'], ['Helvoirt', 'Noord-Brabant'],
    ['Haaren', 'Noord-Brabant'], ['Nemerselaer', 'Noord-Brabant'], ['Boskamp', 'Noord-Brabant'],
    ['Olland', 'Noord-Brabant'], ['Lierop', 'Noord-Brabant'], ['Heeze', 'Noord-Brabant'],
    ['Leende', 'Noord-Brabant'], ['Sterksel', 'Noord-Brabant'], ['Maarheeze', 'Noord-Brabant'],
    ['Budel', 'Noord-Brabant'], ['Budel-Schoot', 'Noord-Brabant'], ['Budel-Dorplein', 'Noord-Brabant'],
    ['Gastel', 'Noord-Brabant'], ['Soerendonk', 'Noord-Brabant'], ['Kaulille', 'Noord-Brabant'],
    ['Wintelre', 'Noord-Brabant'], ['Vessem', 'Noord-Brabant'], ['Knegsel', 'Noord-Brabant'],
    ['Steensel', 'Noord-Brabant'], ['Duizel', 'Noord-Brabant'], ['Hapert', 'Noord-Brabant'],
    ['Casteren', 'Noord-Brabant'], ['Hoogeloon', 'Noord-Brabant'], ['Netersel', 'Noord-Brabant'],
    ['Luyksgestel', 'Noord-Brabant'], ['Riethoven', 'Noord-Brabant'], ['Westerhoven', 'Noord-Brabant'],
    ['Borkel en Schaft', 'Noord-Brabant'], ['Dommelen', 'Noord-Brabant'], ['Eindhoven', 'Noord-Brabant'],
    ['Aalst', 'Noord-Brabant'], ['Ekenrooi', 'Noord-Brabant'], ['Oerle', 'Noord-Brabant'],
    ['Zandoerle', 'Noord-Brabant'], ['Tinteloo', 'Noord-Brabant'], ['Gerwen', 'Noord-Brabant'],
    ['Nederwetten', 'Noord-Brabant'], ['Eeneind', 'Noord-Brabant'], ['Sint-Oedenrode', 'Noord-Brabant'],
    ['Mariaheide', 'Noord-Brabant'], ['Zijtaart', 'Noord-Brabant'], ['Eerde', 'Noord-Brabant'],
    ['Boerdonk', 'Noord-Brabant'], ['Keldonk', 'Noord-Brabant'], ['Erp', 'Noord-Brabant'],
    ['Dinther', 'Noord-Brabant'], ['Heeswijk', 'Noord-Brabant'], ['Vorstenbosch', 'Noord-Brabant'],
    ['Fijnaart', 'Noord-Brabant'], ['Heijningen', 'Noord-Brabant'], ['Dinteloord', 'Noord-Brabant'],
    ['Steenbergen', 'Noord-Brabant'], ['Nieuw-Vossemeer', 'Noord-Brabant'], ['De Heen', 'Noord-Brabant'],
    ['Kruisland', 'Noord-Brabant'], ['Oudenbosch', 'Noord-Brabant'], ['Oud Gastel', 'Noord-Brabant'],
    ['Stampersgat', 'Noord-Brabant'], ['Bosschenhoofd', 'Noord-Brabant'], ['Hoeven', 'Noord-Brabant'],
    ['Rucphen', 'Noord-Brabant'], ['Sprundel', 'Noord-Brabant'], ['Schijf', 'Noord-Brabant'],
    ['Sint Willebrord', 'Noord-Brabant'], ['Zegge', 'Noord-Brabant'], ['Moerstraten', 'Noord-Brabant'],
    ['Wouw', 'Noord-Brabant'], ['Wouwse Plantage', 'Noord-Brabant'], ['Heerle', 'Noord-Brabant'],
    ['Moerstraten', 'Noord-Brabant'], ['Nispen', 'Noord-Brabant'], ['Essen', 'Antwerpen'],
    ['Kalmthout', 'Antwerpen'], ['Putte', 'Antwerpen'], ['Hogerheide', 'Noord-Brabant'],
    ['Halsteren', 'Noord-Brabant'], ['Lepelstraat', 'Noord-Brabant'], 
    ['Hoogerheide', 'Noord-Brabant'], ['Woensdrecht', 'Noord-Brabant'], ['Huijbergen', 'Noord-Brabant'],
    ['Ossendrecht', 'Noord-Brabant'], ['Putte', 'Antwerpen'], ['Willemstad', 'Noord-Brabant'],
    ['Heijningen', 'Noord-Brabant'], ['Klundert', 'Noord-Brabant'], ['Standdaarbuiten', 'Noord-Brabant'],
    ['Oud en Nieuw Gastel', 'Noord-Brabant'], ['Zevenbergen', 'Noord-Brabant'], ['Zeberbergen', 'Noord-Brabant'],
    ['Moerdijk', 'Noord-Brabant'], ['Fijnaart', 'Noord-Brabant'], ['Langeweg', 'Noord-Brabant'],
    ['Lage Zwaluwe', 'Noord-Brabant'], ['Terheijden', 'Noord-Brabant'], ['Wagenberg', 'Noord-Brabant'],
    ['Hooge Zwaluwe', 'Noord-Brabant'], ['Made', 'Noord-Brabant'], ['Drimmelen', 'Noord-Brabant'],
    ['Geertruidenberg', 'Noord-Brabant'], ['Raamsdonksveer', 'Noord-Brabant'], ['Raamsdonk', 'Noord-Brabant'],
    ['Oosterhout', 'Noord-Brabant'], ['Dorst', 'Noord-Brabant'], ['Den Hout', 'Noord-Brabant'],
    ['Oosteind', 'Noord-Brabant'], ['Teteringen', 'Noord-Brabant'],
    ['Bavel', 'Noord-Brabant'], ['Ulvenhout', 'Noord-Brabant'], ['Ginneken', 'Noord-Brabant'],
    ['Princenhage', 'Noord-Brabant'], ['Etten-Leur', 'Noord-Brabant'], ['Zundert', 'Noord-Brabant'],
    ['Rijsbergen', 'Noord-Brabant'], ['Wernhout', 'Noord-Brabant'], ['Achtmaal', 'Noord-Brabant'],
    ['Klein Zundert', 'Noord-Brabant'], ['Chaam', 'Noord-Brabant'], ['Alphen', 'Noord-Brabant'],
    ['Hulsel', 'Noord-Brabant'], ['Lage Mierde', 'Noord-Brabant'], ['Hooge Mierde', 'Noord-Brabant'],
    ['Reusel', 'Noord-Brabant'], ['Middelbeers', 'Noord-Brabant'], ['Oostelbeers', 'Noord-Brabant'],
    ['Vessem', 'Noord-Brabant'], ['Spoordonk', 'Noord-Brabant'],

    // ---- Limburg ----
    ['Maastricht', 'Limburg'], ['Venlo', 'Limburg'], ['Heerlen', 'Limburg'],
    ['Sittard', 'Limburg'], ['Geleen', 'Limburg'], ['Weert', 'Limburg'],
    ['Roermond', 'Limburg'], ['Kerkrade', 'Limburg'], ['Landgraaf', 'Limburg'],
    ['Brunssum', 'Limburg'], ['Gennep', 'Limburg'], ['Venray', 'Limburg'],
    ['Horst', 'Limburg'], ['Panningen', 'Limburg'], ['Helden', 'Limburg'],
    ['Tegelen', 'Limburg'], ['Belfeld', 'Limburg'], ['Stein', 'Limburg'],
    ['Elsloo', 'Limburg'], ['Beek', 'Limburg'], ['Born', 'Limburg'],
    ['Echt', 'Limburg'], ['Susteren', 'Limburg'], ['Maasbracht', 'Limburg'],
    ['Wessem', 'Limburg'], ['Thorn', 'Limburg'], ['Melick', 'Limburg'],
    ['Swalmen', 'Limburg'], ['Valkenburg', 'Limburg'], ['Margraten', 'Limburg'],
    ['Gulpen', 'Limburg'], ['Vaals', 'Limburg'], ['Simpelveld', 'Limburg'],
    ['Voerendaal', 'Limburg'], ['Nuth', 'Limburg'], ['Schinnen', 'Limburg'],
    ['Amstenrade', 'Limburg'], ['Oirsbeek', 'Limburg'], ['Doenrade', 'Limburg'],
    ['Munstergeleen', 'Limburg'], ['Windraak', 'Limburg'], ['Buchten', 'Limburg'],
    ['Grevenbicht', 'Limburg'], ['Papenhoven', 'Limburg'], ['Obbicht', 'Limburg'],
    ['Illikhoven', 'Limburg'], ['Roosteren', 'Limburg'], ['Susteren', 'Limburg'],
    ['Nieuwstadt', 'Limburg'], ['Sint Odiliënberg', 'Limburg'], ['Herkenbosch', 'Limburg'],
    ['Vlodrop', 'Limburg'], ['Posterholt', 'Limburg'], ['Montfort', 'Limburg'],
    ['Linne', 'Limburg'], ['Stevensweert', 'Limburg'], ['Ohé en Laak', 'Limburg'],
    ['Beegden', 'Limburg'], ['Heel', 'Limburg'], ['Panheel', 'Limburg'],
    ['Buggenum', 'Limburg'], ['Nunhem', 'Limburg'], ['Haelen', 'Limburg'],
    ['Horn', 'Limburg'], ['Baexem', 'Limburg'], ['Ell', 'Limburg'],
    ['Grathem', 'Limburg'], ['Kelpen-Oler', 'Limburg'], ['Roggel', 'Limburg'],
    ['Heythuysen', 'Limburg'], ['Baarlo', 'Limburg'], ['Kessel', 'Limburg'],
    ['Beringe', 'Limburg'], ['Maasbree', 'Limburg'], ['Lottum', 'Limburg'],
    ['Grubbenvorst', 'Limburg'], ['Broekhuizenvorst', 'Limburg'], ['Broekhuizen', 'Limburg'],
    ['Arcen', 'Limburg'], ['Lomm', 'Limburg'], ['Velden', 'Limburg'],
    ['Blerick', 'Limburg'], ['Boekend', 'Limburg'], ['Hout-Blerick', 'Limburg'],
    ['Heerlerheide', 'Limburg'], ['Hoensbroek', 'Limburg'], ['Nuth', 'Limburg'],
    ['Wijnandsrade', 'Limburg'], ['Hulsberg', 'Limburg'], ['Klimmen', 'Limburg'],
    ['Ransdaal', 'Limburg'], ['Schimmert', 'Limburg'], ['Geulle', 'Limburg'],
    ['Bunde', 'Limburg'], ['Meerssen', 'Limburg'], ['Moorveld', 'Limburg'],
    ['Ulestraten', 'Limburg'], ['Rothem', 'Limburg'], ['Itteren', 'Limburg'],
    ['Borgharen', 'Limburg'], ['Scharn', 'Limburg'], ['Heugem', 'Limburg'],
    ['Oud-Valkenburg', 'Limburg'], ['Schin op Geul', 'Limburg'], ['Walem', 'Limburg'],
    ['Berg en Terblijt', 'Limburg'], ['Sibbe', 'Limburg'], ['IJzeren', 'Limburg'],
    ['Houthem', 'Limburg'], ['Meerssen', 'Limburg'], ['Groot Haasdal', 'Limburg'],
    ['Klein Haasdal', 'Limburg'], ['Sweikhuizen', 'Limburg'], ['Puth', 'Limburg'],
    ['Doenrade', 'Limburg'], ['Merkelbeek', 'Limburg'], ['Bingelrade', 'Limburg'],
    ['Jabeek', 'Limburg'], ['Schinveld', 'Limburg'], ['Echt', 'Limburg'],
    ['Koningsbosch', 'Limburg'], ['Maria Hoop', 'Limburg'], ['Sint Joost', 'Limburg'],
    ['Pey', 'Limburg'], ['Heide', 'Limburg'], ['Dieteren', 'Limburg'],
    ['Nieuw Bergen', 'Limburg'], ['Bergen', 'Limburg'], ['Afferden', 'Limburg'],
    ['Well', 'Limburg'], ['Wellerlooi', 'Limburg'], ['Siebengewald', 'Limburg'],
    ['Ottersum', 'Limburg'], ['Heijen', 'Limburg'], ['Milsbeek', 'Limburg'],
    ['Middelaar', 'Limburg'], ['Mook', 'Limburg'], ['Plasmolen', 'Limburg'],
    ['Reek', 'Noord-Brabant'], ['Zeeland', 'Noord-Brabant'],
    ['Escharen', 'Noord-Brabant'], ['Oeffelt', 'Noord-Brabant'], ['Beugen', 'Noord-Brabant'],
    ['Boxmeer', 'Noord-Brabant'], ['Sambeek', 'Noord-Brabant'], ['Vortum-Mullem', 'Noord-Brabant'],
    ['Vierlingsbeek', 'Noord-Brabant'], ['Groeningen', 'Noord-Brabant'], ['Overloon', 'Noord-Brabant'],
    ['Holthees', 'Noord-Brabant'], ['Smakt', 'Noord-Brabant'], ['Venray', 'Limburg'],
    ['Ysselsteyn', 'Limburg'], ['Merselo', 'Limburg'], ['Vredepeel', 'Limburg'],
    ['Castenray', 'Limburg'], ['Oostrum', 'Limburg'], ['Leunen', 'Limburg'],
    ['Heide', 'Limburg'], ['Lom', 'Limburg'],

    // ---- België ----
    ['Antwerpen', 'Antwerpen'],
];
